date.timezone = Asia/Bangkok
default_charset = "UTF-8"
upload_max_filesize = 10M
post_max_size = 12M
memory_limit = 256M
expose_php = Off
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.use_strict_mode = 1
display_errors = On
error_reporting = E_ALL
